# Site settings
title: Stephenchow | La senda solitaria
description: "La senda solitaria"
url: "cultvonnegut.github.io"
author:
  name: "Juan M. Jimenez"
  email: "bodypheo@gmail.com"
  url: "cultvonnegut.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

gems: [jekyll-paginate]
# Options
custom_header: false
custom_nav_footer: false
reverse: false
